// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrzfznhijgriuoqflrgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyemZ6bmhpamdyaXVvcWZscmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDY3MjcsImV4cCI6MjA2NjYyMjcyN30.vf5ol7BQM40ev2y-_Gzpg0Bpb1lmmSBc7HemLAPAV_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);